from enum import Enum


class ErrorCode(str, Enum):
    SCHEDULE_CONFLICT = "SCHEDULE_CONFLICT"
    APPOINTMENT_NOT_FOUND = "APPOINTMENT_NOT_FOUND"
    USER_NOT_AUTHORIZED = "USER_NOT_AUTHORIZED"
    TENANT_INVALID = "TENANT_INVALID"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
    INTERNAL_ERROR = "INTERNAL_ERROR"
