from enum import Enum


class ErrorCode(str, Enum):
    CONFLITO_AGENDA = "CONFLITO_AGENDA"
    COMPROMISSO_NAO_ENCONTRADO = "COMPROMISSO_NAO_ENCONTRADO"
    USUARIO_NAO_AUTORIZADO = "USUARIO_NAO_AUTORIZADO"
    TENANT_INVALIDO = "TENANT_INVALIDO"
    VALIDACAO_FALHOU = "VALIDACAO_FALHOU"
    RATE_LIMIT_EXCEDIDO = "RATE_LIMIT_EXCEDIDO"
    ERRO_INTERNO = "ERRO_INTERNO"
