"""criar tabela companies

Revision ID: 06b0bc232d22
Revises: 
Create Date: 2026-03-02 10:05:24.584010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06b0bc232d22'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply schema upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('identificador', sa.String(length=150), nullable=False),
    sa.Column('plano', sa.Enum('FREE', 'PRO', 'ENTERPRISE', name='company_plan_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identificador')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('companies')
    # ### end Alembic commands ###
